### ISSUE TITLE
What's the best way to detect connection status?

### ISSUE THREAD

**Issue by gtamas** [mixer/etcd3#105]
Hi

How can I detect (on app startup) whether the client is actually connected to ETCD or not? 

I would like to determine whether the client is ready to send ETCD requests or not. If connecting to ETCD has failed (for any reason), I want to show the settings screen and no other part of the app should be accessible until the user configures everything properly and successfully connects the app to ETCD.

What's the best way to achieve this?

I don't really see any public API dealing with connections and related stuff.

Thanks in advance!

**Comment by gtamas** [comment]
@connor4312 

I'm sure there is a way to do this. The problem is when you do:

```
const client = new Ectd3()
```

This is sync op. But in the background it's trying to connect to ETCD and this results in unhandled promise error. I can't catch this error.

**Comment by connor4312** [comment]
I'm unable to reproduce this issue. The client doesn't deal with persistent connections outside of watch streams--that's why you don't see any public APIs for dealing with connections 🙂. Etcd 3 uses grpc which is built upon HTTP/2 and there is an underlying connection pool, but like Node's standard http functionality this isn't exposed or managed by us. The client shouldn't be trying to do anything when it's initially booted.

```
> new Etcd3();
// no error
> new Etcd3().get('foo').then(console.log).catch(console.log);
> GRPCConnectFailedError: 14 UNAVAILABLE: failed to connect to all addresses
    at Object.exports.createStatusError (/mnt/d/Github/etcd3/node_modules/grpc/src/common.js:91:15)
    at Object.onReceiveStatus (/mnt/d/Github/etcd3/node_modules/grpc/src/client_interceptors.js:1204:28)
    at InterceptingListener._callNext (/mnt/d/Github/etcd3/node_modules/grpc/src/client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (/mnt/d/Github/etcd3/node_modules/grpc/src/client_interceptors.js:618:8)
    at callback (/mnt/d/Github/etcd3/node_modules/grpc/src/client_interceptors.js:845:24)
```

**Comment by gtamas** [comment]
Ahh ok I see. Thanks for the clarification.

**Comment by lerit** [comment]
@gtamas   i face same problem.
do you mean that if i use new etcd3(),i can not caught GRPCConnectFailedError(by promise.catch or await try catch) and 
the only place is in:
 process.on('unhandledRejection',(err)=>{})
would you please give me some suggestion
