### ISSUE TITLE
Lease renewal during locking?

### ISSUE THREAD

**Issue by djMax** [mixer/etcd3#106]
I'm porting some locking code from https://github.com/boltsource/microlock - one thing it supports is renewal of a lock, which allows a low timeout but the ability for the executing code to say "I'm still here, don't release me!" - is it possible to do that in this module?

**Comment by connor4312** [comment]
Yep. That's actually handled automatically, internally. Lock docs are [here](https://mixer.github.io/etcd3/classes/lock_.lock.html), you can either:

1: use `do()`, which will acquire the lock and keep it alive until the promise returned by the function resolves or rejects

```
client.lock('my_resource').do(async () => {
  await doMyAtomicAction();
});
```


2: use `acquire()` and `release()`. While a lock is acquired, it'll 'hearbeat', until you call `release()`. This is equivalent to the above code:

```
const lock = client.lock('my_resource');

await lock.acquire();

try {
  await doMyAtomicAction();
} finally {
  await lock.release();
}
```

**Comment by djMax** [comment]
Ok, so that means the ttl on a lock should be the “maximum time I will wait if a process blows up and doesn’t release its lease?” As opposed to “the maximum time my function can take to complete” which is infinite here?

Also it seems that if someone else has the lock, it will fail immediately? This is fine, as I can just back off and retry the acquire in that case

**Comment by connor4312** [comment]
> Ok, so that means the ttl on a lock should be the “maximum time I will wait if a process blows up and doesn’t release its lease?” As opposed to “the maximum time my function can take to complete” which is infinite here?

Yea, that's accurate. We don't support having a 'hard cutoff', that's up to the consumer to cancel whatever operation they're doing if they think it's taking too long.

> Also it seems that if someone else has the lock, it will fail immediately? This is fine, as I can just back off and retry the acquire in that case

Also correct :) Adding built-in backoffs would be useful, but I want to give some thought to its implementation. I wish there was a rich de-facto library for that in Node.js, like [Polly](https://github.com/App-vNext/Polly) in .NET that we could grab and toss in. I'll need to do some more research here; suggestions welcome.

**Comment by djMax** [comment]
I already had that backoff logic in our code, so it's easy enough for me to keep, but I would assume some sort of tryAcquire(howLongToWait, backoffStrategy) type of API on the lock would be a nice helper.
