### ISSUE TITLE
Cannot use user/pass auth w/o ssl

### ISSUE THREAD

**Issue by txchen** [mixer/etcd3#20]
Tried to create client like this:

`new Etcd3({ hosts: conf.etcdurl, auth: { username: 'readonly', password: 'readonly' } })`

Error is like this:

```
unexpected error:  TypeError: Cannot compose insecure credential
    at Object.exports.combineChannelCredentials (/Users/xxx/node_modules/grpc/src/node/src/credentials.js:151:23)
    at getCredentialsFromHost.then.token (/Users/xxx/node_modules/etcd3/lib/src/connection-pool.js:62:41)
    at <anonymous
```

Maybe this is related: https://stackoverflow.com/questions/37526077/how-to-add-metadata-to-nodejs-grpc-call

**Comment by connor4312** [comment]
This is a 'by design', GRPC does not allow sending credentials over insecure transports.

In a scenario where you need to authenticate, it's always a good idea to use TLS

**Comment by txchen** [comment]
Hmm, then why my etcdctl can still work without enable tls in the server side?

**Comment by connor4312** [comment]
etcdctl uses the [Go implementation of GRPC](https://github.com/grpc/grpc-go), which is separate from the [standard cross-language version](https://github.com/grpc/grpc). The Go version probably does not enforce this check.

I would again note, however, that the cases where you want to use TLS are a superset of cases where you want to use password auth. If you're going over a public network, you _definitely_ want TLS. If you're inside a private VIP you still should use TLS, as it's been demonstrated that there are adversaries capable of intercepting inter and intra-datacenter network traffic.

**Comment by gtamas** [comment]
I can see there are several old issues about SSL / TLS. 
What's the status of this? Does it work fine with the current version?

I tried to check the docs, but I'm still not sure about how to use this SSL / TLS feature.
I can see I am supposed to pass an IOptions object to Etcd3 constructor with a "credentials" key. But how does this credentials object look like? The link in the docs just points to the ETCD homepage.

And etcdctl seems to take several ssl related arguments (like cert file, key file, root cert etc). Am I supposed to pass these in the credentials object??

```
new Etcd3({
credentials: {
// What's in here??
}
})
```

Thanks in advance!

**Comment by connor4312** [comment]
Looks like the typedocs don't show the full object definition. Here's how we use the credentials:

https://github.com/mixer/etcd3/blob/0ffcec967695894a93cf321efceae787f84f8213/src/connection-pool.ts#L311-L315

**Comment by gtamas** [comment]
OK thanks!
