### ISSUE TITLE
cant set ttl when using lock

### ISSUE THREAD

**Issue by lenew** [mixer/etcd3#25]
var lock = client.lock('foo');
lock.ttl(3); //this will throw an exception "Cannot set a lock TTL after acquiring the lock"
lock.then(...)

solution:
src/lock.ts function ttl(
if (!this.lease) => if(this.lease)

**Comment by connor4312** [comment]
Thanks for opening an issue! This is fixed in https://github.com/mixer/etcd3/pull/26 and published in 0.2.3.
