### ISSUE TITLE
Etcd watch response order

### ISSUE THREAD

**Issue by styleex** [mixer/etcd3#30]
WatchManager has potencial bug: etcd does not give guarantees about WatchResponse 
 (https://github.com/coreos/etcd/issues/7036)

**Comment by connor4312** [comment]
Thanks for opening an issue! To clarify, you're referring to the problem discussed in this comment https://github.com/coreos/etcd/issues/7036#issuecomment-268032094?

**Comment by styleex** [comment]
yes. In my mini lib on python I consistently initialize each observer. Those. First I wait for an answer to the first request, then I send the second one and wait for an answer, and so on. This works fine

**Comment by connor4312** [comment]
Thanks for the issue! Fix submitted in the linked PR

**Comment by connor4312** [comment]
Fixed in https://github.com/mixer/etcd3/pull/33
