### ISSUE TITLE
After reconnect watchers no receive events 

### ISSUE THREAD

**Issue by styleex** [mixer/etcd3#31]
My code is:

```
        const watcher = await etcd.watch().prefix('...').create();

        watcher.on('put', (res) => {
          console.log('put');
        });

        watcher.on('delete', (res) => {
           console.log('delete');
        });
        watcher.on('disconnected', () => console.log('disconnected...'));
        watcher.on('connected', () => console.log('successfully reconnected!'));
```

In normal case this code work is correct. After stop and start etcd on console i see this lines: 
```
disconnected...
successfully reconnected!
```

But the events no longer come.

**Comment by connor4312** [comment]
Thanks for the issue! I submitted a PR for it ^ please let me know if you think that solves what you're seeing

**Comment by styleex** [comment]
#31 Hmm, now I'm trying to prove the problem again, but it does not reproduce (on the latest release of the library). Last time, I did not do anything except start the script. Maybe my previous test was incorrect.

**Comment by connor4312** [comment]
Fixed in https://github.com/mixer/etcd3/pull/33
