### ISSUE TITLE
Question about moment between `WatchBuilder.create()` and `watcher.on('put', ...)`

### ISSUE THREAD

**Issue by styleex** [mixer/etcd3#32]
Is it possible to miss the etcd events, in the event that Watcher.create already occurred, but the event handler is not yet assigned to the watcher?

In code:
```
        const watcher = await etcd.watch().prefix('...').create();
        // 

        // Is there any chance to miss an etcd events in this moment?

        //
        watcher.on('put', (res) => {
             ....
        });

```

**Comment by connor4312** [comment]
It's not. Internally .create() listens to the [connected](https://github.com/mixer/etcd3/blob/master/src/watch.ts#L321) event then resolves the promise. Events are dispatched synchronously and promise resolution happens as a microtask. Callbacks from the grpc to Node code happen as macrotasks; microtasks will always take precedence.
