### ISSUE TITLE
Feature request: API for software transactional memory (STM)

### ISSUE THREAD

**Issue by styleex** [mixer/etcd3#34]
The golang client provides an implementation of STM. This API is very useful for applications that update a lot of related keys in parallel.

For example, in my application several administrators can modify the system settings in parallel. However, some settings are related.

Now it has to be implemented manually, because of what the convenience of the API provided by this library is lost (I mean the `.json()` method and others)

More information about the topic:

https://coreos.com/blog/transactional-memory-with-etcd3.html
https://godoc.org/github.com/coreos/etcd/clientv3/concurrency#STM

**Comment by connor4312** [comment]
Thanks for the issue! This sounds like a good idea. Unfortunately I won't have time to implement it for ~2 weeks or so. I would welcome PRs for some or all of this functionality if you're interested in submitting them 😄

**Comment by drewfish** [comment]
I wonder if it makes sense to implement this as a separate npm package, built on top of this `etcd3` package.

**Comment by connor4312** [comment]
I have an initial implementation of this in https://github.com/mixer/etcd3/pull/39
