### ISSUE TITLE
GRPCConnectFailedError: Connect Failed

### ISSUE THREAD

**Issue by zyf0330** [mixer/etcd3#35]
This is my constructor code
```
const etcd = new Etcd3({
	hosts: ['https://example1.com:4758', 'https://example2.com:4758', 'https://example3.com:4758'],
	auth: {username: username, password: pwd},
});
```
And I got this error 
```
GRPCConnectFailedError: Connect Failed\n    at /media/zyf/data/Programming/project/duobei/duobeiyun-mobile-server/node_modules/etcd3/node_modules/grpc/src/node/src/client.js:569:15
```
What happened?

**Comment by zyf0330** [comment]
Another thing. 
I see  that `augmentCredentials` method in connection-pool.js has a problem. when attempting enough times causes `Promise.reject(previousRejection);`, this rejection won't be handled and console gives this `(node:30481) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: Connect Failed`. 
This is confusing.

**Comment by connor4312** [comment]
Thanks for the issue. The connection failed error is most likely an issue with you setup or configuration, not the client itself. If not, then it's one on the GRPC core.

The unhandled rejection is fixed in https://github.com/mixer/etcd3/commit/58c08be8d157fed1588c3d26aa569e10f7f5817f
