### ISSUE TITLE
GRPCGenericError: Received message larger than max

### ISSUE THREAD

**Issue by styleex** [mixer/etcd3#36]
nodejs[20647]: error: main failed: GRPCGenericError: Received message larger than max (10082828 vs. 4194304)

**Comment by styleex** [comment]
This is not a bug. I've requested too many keys at a time

**Comment by styleex** [comment]
Is there a way to throw a parameter "grpc.max_send_message_length" into the grpc channel?

**Comment by connor4312** [comment]
Good call, we should expose all [grpc options](https://grpc.io/grpc/cpp/group__grpc__arg__keys.html) to the client.

**Comment by connor4312** [comment]
Fixed in https://github.com/mixer/etcd3/commit/378f7c5c73644956dc444d12e9df99cb764b1d09
