### ISSUE TITLE
Application level heartbeat

### ISSUE THREAD

**Issue by styleex** [mixer/etcd3#37]
In some cases (code errors, network errors, etc.), the watcher may silently hang. As one of the security tools etcd offers an application level heartbeat based on the `progress_notify` parameter when creating a watcher.
Perhaps such a functional would be useful in the library.

As far as I know, this approach is used, at least in libraries, to RabbitMQ to detect network problems.
I created a question to clarify how this option works: https://github.com/coreos/etcd/issues/8495

**Comment by connor4312** [comment]
Thanks for the issue! grpc actually has built-in keepalives via http/2 pings, which [are configurable](https://grpc.io/grpc/cpp/group__grpc__arg__keys.html#gaf50a9992745183e14e8c660d954c1d82, and whose options I will expose in fixing #36. I think this suffices for what you're after.
