### ISSUE TITLE
Enable auth with http

### ISSUE THREAD

**Issue by reptilbud** [mixer/etcd3#40]
Hi

I try to use your library to connect etcd but it always fail to do something.

We are using http but we have an authentication with username + password to access it.

When I let the library as it is, I get:

```
Error: grpc does not allow you to use password authentication without connecting over SSL.
```

But when I comment the related line in the file ```connection-pool.js```:

```javascript
buildAuthentication() {
        const { credentials } = this.options;
        let protocolCredentials = grpc.credentials.createInsecure();
        if (credentials) {
            protocolCredentials = grpc.credentials.createSsl(credentials.rootCertificate, credentials.privateKey, credentials.certChain);
        }
        else if (this.hasSecureHost()) {
            protocolCredentials = grpc.credentials.createSsl();
        }
        // else if (this.options.auth) {
        //     throw new Error('grpc does not allow you to use password authentication without connecting ' +
        //         'over SSL. See how to set up etcd with ssl here: https://git.io/v7uhX');
        // }
        return this.authenticator.augmentCredentials(protocolCredentials);
    }
```

It does not throw any error AND I can not perform any action with this snippet of code:

```javascript
const { Etcd3 } = require('etcd3');
const client = new Etcd3({
    hosts: 'http://my.domain.com:2379',
    auth: {
        username: 'my_username',
        password: 'my_password'
    }
});

client
  .get('foo')
  .string()
  .then(_ => console.log('GOT => ', _))
  .catch(err => console.log('ERR => ', err));

```

It is always waiting for something that didn't come...

If you have any idea how I can do to get a result, it would be very cool !

Thanks

**Comment by connor4312** [comment]
This duplicates https://github.com/mixer/etcd3/issues/20. The tl;dr is:

> This is a 'by design', GRPC does not allow sending credentials over insecure transports... You can see a tutorial on how to set up etcd with TLS here: https://github.com/kelseyhightower/etcd-production-setup
>
> ...
>
> I would emphasize, however, that the cases where you want to use TLS are a superset of cases where you want to use password auth. If you're going over a public network, you definitely want TLS. If you're inside a private VIP you still should use TLS, as it's been demonstrated that there are adversaries capable of intercepting inter and intra-datacenter network traffic.

Let me know if you have any other questions 😄

**Comment by reptilbud** [comment]
Yeah... I know but I think this is the responsibility of the develop not of the library no ?
Cause we need to do so internally and with your lib... I just can't... Is there no possibility to see that working one day ?

**Comment by connor4312** [comment]
You can raise the issue with [grpc](https://github.com/grpc/grpc-node), this is a restriction imposed by grpc, not this library.

**Comment by connor4312** [comment]
For clarity, that throw was added to provide a more verbose alternative over what grpc would otherwise provide if we try to set up password credentials on an insecure channel:

```
unexpected error:  TypeError: Cannot compose insecure credential
    at Object.exports.combineChannelCredentials (/Users/xxx/node_modules/grpc/src/node/src/credentials.js:151:23)
    at getCredentialsFromHost.then.token (/Users/xxx/node_modules/etcd3/lib/src/connection-pool.js:62:41)
    at <anonymous
```

**Comment by reptilbud** [comment]
What is weird is that some people here are using a Python client and GRPC let them do this. In their official documentation, they do not said this is mandatory but they said this is better to do so...

**Comment by reptilbud** [comment]
Moreover, with official tool etcdctl, if I do 
```
ETCDCTL_API=3 etcdctl --user="root:<redacted>" --insecure-transport=true --endpoints=[192.168.X.Y:2379] role list
```
on the non ssl endpoint, it works very well.

**Comment by reptilbud** [comment]
I make a pull request for that, if you want to have a look at it
If you don't want this feature please let me know to publish it independently of your repo
Thanks a lot for your time
Cheers

**Comment by reptilbud** [comment]
@connor4312 be carreful, I checked your code and your forgot to give the metadata for the Watch client

```javascript
/* rpc#WatchClient */
watch() {
    return this.client.getConnection('Watch').then(cnx => cnx.client.watch());
}
```

Should be

```javascript
/* rpc#WatchClient */
watch() {
    return this.client.getConnection('Watch').then(cnx => cnx.client.watch(cnx.metadata));
}
```

You maybe missed this part for others like the lease one..
