### ISSUE TITLE
Types inside "Lock" file are not exported

### ISSUE THREAD

**Issue by reptilbud** [mixer/etcd3#45]
If you can export types presents inside the file ```lock.ts``` it would be great to for the next release

**Comment by reptilbud** [comment]
Will do a PR as soon as the ```npm run build:proto``` command will work

**Comment by connor4312** [comment]
I've got a fix staged for this in #47 already (I'll fix the build there tonight probably). Thanks for your willingness to contribute, though! 😄

**Comment by reptilbud** [comment]
No prob :D

**Comment by connor4312** [comment]
Fixed in 0.2.6.
