### ISSUE TITLE
when lease lost, lease state is not revoked

### ISSUE THREAD

**Issue by zyf0330** [mixer/etcd3#52]
https://github.com/mixer/etcd3/blob/05b85c3e4085a0bb00a1c4ff7684935b6b2a1b61/src/lease.ts#L247

Hello, I think logic here is not correct. After `lost` is emitted, `this.close()` is called and `this.state = State.Revoked` is set, so when `on('lost')` `lease.revoked() === false`.

**Comment by connor4312** [comment]
Fixed in https://github.com/mixer/etcd3/pull/53

**Comment by connor4312** [comment]
Published in 0.2.7
