### ISSUE TITLE
Lock never unlocks with lease

### ISSUE THREAD

**Issue by rselbach** [mixer/etcd3#56]
Hi, we're trying to use distributed locking in a project but we're having some trouble getting them to work. Maybe we don't get how they're supposed to work. We have a little test case here that should reproduce the problem:

```
package main

import (
	"context"
	"fmt"
	"log"

	"time"

	"github.com/coreos/etcd/clientv3"
	"github.com/coreos/etcd/clientv3/concurrency"
)

func main() {
	cli, err := clientv3.New(clientv3.Config{Endpoints: []string{"localhost:2379"}})
	if err != nil {
		log.Fatal(err)
	}
	defer cli.Close()

	// get a grant
	ctxc, cancelc := context.WithTimeout(context.Background(), 1*time.Second)
	lresp, err := cli.Grant(ctxc, 2)
	if err != nil {
		log.Fatal(err)
	}
	defer cancelc()
	fmt.Println("lease", lresp.ID)

	// create two separate sessions for lock competition
	s1, err := concurrency.NewSession(cli, concurrency.WithLease(lresp.ID))
	if err != nil {
		log.Fatal(err)
	}
	defer s1.Close()
	m1 := concurrency.NewMutex(s1, "/xxxsx/")

	s2, err := concurrency.NewSession(cli)
	if err != nil {
		log.Fatal(err)
	}
	defer s2.Close()
	m2 := concurrency.NewMutex(s2, "/xxxsx/")

	// acquire lock for s1
	ctx, cancel := context.WithTimeout(context.Background(), 2*time.Second)
	if err := m1.Lock(ctx); err != nil {
		log.Fatal("timeout", err)
	}
	defer cancel()
	fmt.Println("acquired lock for s1")

	m2Locked := make(chan struct{})
	go func() {
		defer close(m2Locked)
		// wait until s1 is unlocked /xxxsx/
		if err := m2.Lock(context.TODO()); err != nil {
			log.Fatal(err)
		}
	}()

	<-m2Locked
	fmt.Println("acquired lock for s2")
}
```

As you can see, we get a grant with a TTL of 2 seconds : 

`lresp, err := cli.Grant(ctxc, 2)`

And this lease is used when we create the section:

`s1, err := concurrency.NewSession(cli, concurrency.WithLease(lresp.ID))`

We manage to acquire the lock correctly the first time, but the second `Lock` (from a goroutine) never returns.

Shouldn't the lock be unlocked when the lease expires?

**Comment by rselbach** [comment]
Ops, posted to the wrong repo. Please disregard :-}

**Comment by connor4312** [comment]
No worries :) @rselbach the issue is that the lease doesn't time out, when you pass it to a concurrency.NewSession, the sessions [keeps the lease alive](https://github.com/coreos/etcd/blob/master/clientv3/concurrency/session.go#L54-L69) until the session is ended.
