### ISSUE TITLE
grpc version 1.9.0 breaks getAll()

### ISSUE THREAD

**Issue by mjhilt** [mixer/etcd3#59]
I don't have a good unit test, but the following sequence throws an error:
`etcd.getAll().prefix(myPrefix).strings().then()` --> Error: Argument mismatch in makeUnaryRequest

I can dig deeper if needed, but my guess is you just need to fix your dependency for now.

**Comment by connor4312** [comment]
Thanks for the report, I'll look into it tonight

**Comment by acarl005** [comment]
Same issue here.

**Comment by connor4312** [comment]
Looks like this is a result of https://github.com/grpc/grpc-node/pull/162. I'll lock grpc to 1.8.0 in this module and look into PR'ing a fix to grpc in the morning.

**Comment by connor4312** [comment]
Fixed in https://github.com/mixer/etcd3/commit/7a034e634f56505bbae1a429703d49ea1d85d3ab
