### ISSUE TITLE
watch grpc stream stays open after the last watcher is canceled

### ISSUE THREAD

**Issue by yehiyam** [mixer/etcd3#62]
Following my conclusion from #61 I saw that when the last watch is canceled, the gRPC stream on the client side is closed, and a new one is created when a new watch is requested.
Looking at the etcd prometheus metric etcd_debugging_mvcc_watch_stream_total, the watch stream in the server is not closed, and the count is increasing until the client process exit.
This leads to resource leak in the server.

**Comment by yehiyam** [comment]
@connor4312 Anything progress on this?

**Comment by godu** [comment]
https://github.com/coreos/etcd/issues/9391

**Comment by godu** [comment]
I try to replace all `this.getStream().end();` by `this.getStream().cancel();`.
https://github.com/mixer/etcd3/blob/master/src/watch.ts
It's not a graceful close, but we should provide extra method to force to cut down connection more brutal.

**Comment by monkbroc** [comment]
I'm going to use @godu fork until this issue is resolved in upstream.
https://github.com/CoorpAcademy/etcd3/commit/1905266d949b0272361ae5733e9cf2150d96ac1b
