### ISSUE TITLE
Q: where can i set ttl value?

### ISSUE THREAD

**Issue by jiachaosun** [mixer/etcd3#67]
I know in node-etcd (v2) lib that i could use etcd.set(key, value, {ttl: 10}) to set ttl value.
But I did't found anywhere to set ttl value here in etcd3 lib.

**Comment by connor4312** [comment]
TTLs are replaced by [leases](https://coreos.com/etcd/docs/latest/dev-guide/interacting_v3.html#grant-leases) in etcdv3. Here's docs on this library's API for dealing with leases: https://mixer.github.io/etcd3/classes/lease_.lease.html.
