### ISSUE TITLE
Watcher cannot specify starting revision.

### ISSUE THREAD

**Issue by mikedoug** [mixer/etcd3#77]
This is keenly important to avoid having to use locking.  This is trivial to fix in WatchBuilder class by adding something like this to it:

```
public fromRevision(revision: string, increment: number) {
    this.request.start_revision = new BigNumber(revision).add(increment).toString();
    return this;
}
```

The revision I am passing in here is from a previous call to get all of the keys under a prefix.  I want to be able to tell it to use that revision plus one (hence the increment).  I'm not sure if that is a string or whatnot.  I would have done a pull request myself, but I've not dabbled in Typescript, and when I tried to run the tests unmodified they blew up on me.

**Comment by connor4312** [comment]
This has been added and published in 0.2.12. Thanks for your suggestion!
