### ISSUE TITLE
No way to put multiple keys under folder

### ISSUE THREAD

**Issue by tejinderss** [mixer/etcd3#79]
The put method just provide the put with the key, values as strings. Is there a way to store multiple keys under the single folder to group create/retrieve them ?

**Comment by connor4312** [comment]
You will need to call put multiple times; etcd does not provide bulk insertion.

**Comment by tejinderss** [comment]
Is it possible to fetch in bulk ? Using range .

**Comment by connor4312** [comment]
Yep, getAll starts a range query.

**Comment by tejinderss** [comment]
Is there a way to pass prefix or directory name to that ?

**Comment by connor4312** [comment]
Yes, there is a prefix function. We have API docs: https://mixer.github.io/etcd3/classes/builder_.multirangebuilder.html#prefix

**Comment by tejinderss** [comment]
Sorry to bother but I had a look at this. But get() method doesn't allow me
to pass on prefix to the underlying multirange class. How can I use this ?

Thanks

**Comment by connor4312** [comment]
Use getAll https://mixer.github.io/etcd3/classes/index_.etcd3.html#getall

**Comment by tejinderss** [comment]
Sorry missed this. Thanks a ton for your help
