### ISSUE TITLE
Node v10.6.0

### ISSUE THREAD

**Issue by NassiHarel** [mixer/etcd3#81]
After upgrading to Node v10.6.0 - got this message:
(node:32397) DeprecationWarning: grpc.load: Use the @grpc/proto-loader module with grpc.loadPackageDefinition instead.

Everything works fine, but just want let you know
Thanks.

**Comment by flyinghail** [comment]
Same issue.
This warning is displayed after upgrading to [grpc 1.13.0](https://github.com/grpc/grpc-node/releases/tag/grpc%401.13.0).

**Comment by zyf0330** [comment]
When will this release?
