### ISSUE TITLE
Could I'm use with mongodb node client?

### ISSUE THREAD

**Issue by klikpaspor** [mixer/etcd3#95]
I'm interest with this repo, could i'm use with mongodb node client?

**Comment by connor4312** [comment]
This library is for etcd. We don't have any plans to be compatible with mongodb.

**Comment by klikpaspor** [comment]
i'm not understand etcd, but could you give example how to etcd work with authentication. Because this have doc but littel not all. could you make documentation more detail per function.

**Comment by klikpaspor** [comment]
`public roleGrantPermission(names: string, param: [key: Buffer]| undefined){

        const cb = new Etcd3({hosts: ''});
        cb.auth.roleGrantPermission({name: names, perm: [key: Buffer, permType: "Read" | "Write" | "Readwrite", range_end: Buffer]});
    }`

i'm have some problem to implement roleGrantPermission in public function and the problem in 'perm' its contain multiple interface how to handle it?

**Comment by connor4312** [comment]
API documentation can be found [here](https://mixer.github.io/etcd3/classes/index_.etcd3.html). You can authenticate using password auth like this:

```ts
const client = new Etcd3({
  auth: {
    username: 'foo',
    password: 'bar',
  },
});
```

Docs and types for options: https://github.com/mixer/etcd3/blob/master/src/options.ts#L5
